import { Inter } from "next/font/google";
import { Header } from "./Components/Header/Header";
import Head from "next/head";
import { Navbar } from "./Components/NavBar/Navbar";
import Input from "./Components/Input/Input";
import Resultado from "./Components/Resultado/Resultado";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
        <Navbar typePage={"Pesquisar"} />
        <Input />
        <Resultado/>
      
    </>
  );
}
